# compose.yml
services:
    yt:
        build: 
            context: .
            dockerfile: Dockerfile
        image: teste_f5tts
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        environment:
            - DISPLAY=:0
            - NVIDIA_DRIVER_CAPABILITIES=all
            - NVIDIA_VISIBLE_DEVICES=all
            - DEBUG_COLORS=1
            - TERM=xterm-256color
            - COLORTERM=truecolor
            - CHOKIDAR_USEPOLLING=true
            - PYTHONPATH=${PYTHONPATH}:/app/F5TTS
        volumes:
            - ./:/app:rw
            - ./F5-TTS:/app/F5-TTS
            - ./output_audio:/app/output_audio
            - ./data/huggingface_cache:/root/.cache/huggingface
            - ./data/pip_cache:/root/.cache/pip
            
        ports:
        - "7860:7860"  # Mapeia a porta 7860 do contêiner para a porta 7860 do host
        stdin_open: true  # Entrada interativa
        tty: true
